repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: black
        entry: black .
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort
        args: ["--profile", "black", "."]
  - repo: local
    hooks:
      # Hook para actualizar requirements.txt desde Poetry
      - id: update-requirements
        name: Update requirements.txt from Poetry
        entry: poetry run python manage.py export-requirements
        language: system
        pass_filenames: false
        stages: [pre-commit]
