# Use a lightweight Python base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8080

# Specify the command to run your function
CMD ["functions-framework", "--target=hello_pubsub", "--source=src.pubsub_cloud", "--port=8080"]