"""12_10_2024

Revision ID: 8ccc31d871f1
Revises: a3f2434395cf
Create Date: 2024-10-12 22:57:35.491052

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8ccc31d871f1"
down_revision: Union[str, None] = "a3f2434395cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "task_id", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "videos",
        "score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "videos",
        "score",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column("tasks", "task_id", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
