"""12_10_2024

Revision ID: 97179acb0d5d
Revises: e857c2a715ef
Create Date: 2024-10-12 17:32:32.010057

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "97179acb0d5d"
down_revision: Union[str, None] = "e857c2a715ef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "video_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("tasks", "video_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###
