"""12_10_2024

Revision ID: a3f2434395cf
Revises: bc0fb89946fd
Create Date: 2024-10-12 21:42:58.272083

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3f2434395cf"
down_revision: Union[str, None] = "bc0fb89946fd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("original_video_id", sa.Integer(), nullable=True))
    op.add_column("tasks", sa.Column("processed_video_id", sa.Integer(), nullable=True))
    op.drop_constraint("fk_tasks_video_id_videos", "tasks", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_tasks_original_video_id_videos"),
        "tasks",
        "videos",
        ["original_video_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_tasks_processed_video_id_videos"),
        "tasks",
        "videos",
        ["processed_video_id"],
        ["id"],
    )
    op.drop_column("tasks", "video_id")
    op.drop_column("tasks", "input")
    op.drop_column("tasks", "filename")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks", sa.Column("filename", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "tasks",
        sa.Column(
            "input",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "tasks", sa.Column("video_id", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(
        op.f("fk_tasks_processed_video_id_videos"), "tasks", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_tasks_original_video_id_videos"), "tasks", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_tasks_video_id_videos", "tasks", "videos", ["video_id"], ["id"]
    )
    op.drop_column("tasks", "processed_video_id")
    op.drop_column("tasks", "original_video_id")
    # ### end Alembic commands ###
