"""12_10_2024

Revision ID: bc0fb89946fd
Revises: 97179acb0d5d
Create Date: 2024-10-12 17:36:04.393001

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc0fb89946fd"
down_revision: Union[str, None] = "97179acb0d5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("filename", sa.String(), nullable=True))
    op.execute(
        """
        UPDATE tasks
        SET filename = title
    """
    )
    op.alter_column("tasks", sa.Column("filename", sa.String(), nullable=False))
    op.drop_column("tasks", "title")
    op.alter_column(
        "videos",
        "score",
        existing_type=sa.INTEGER(),
        type_=sa.Float(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "videos",
        "score",
        existing_type=sa.Float(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    op.add_column(
        "tasks",
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("tasks", "filename")
    # ### end Alembic commands ###
