"""12_10_2024

Revision ID: e857c2a715ef
Revises: 85f38347a14f
Create Date: 2024-10-12 17:22:46.594106

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e857c2a715ef"
down_revision: Union[str, None] = "85f38347a14f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.VARCHAR(length=10),
        type_=sa.Enum(
            "pending",
            "uploaded",
            "processed",
            "failure",
            name="taskstatusenum",
            native_enum=False,
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "tasks",
        "status",
        existing_type=sa.Enum(
            "pending",
            "uploaded",
            "processed",
            "failure",
            name="taskstatusenum",
            native_enum=False,
        ),
        type_=sa.VARCHAR(length=10),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
